[http]
listen = "127.0.0.1:3000"

[can]
interface = "can0"

[mqtt]
addr = "altherma-gateway:1883"
username = ""
password = ""

[hass]
mqtt_discovery_prefix = "homeassistant"
device_prefix = "altherma-gateway"

[serial]
path = "/dev/ttyUSB0"
baud_rate = 9600
data_bits = "Eight"
parity = "Even"
stop_bits = "One"
flow_control = "None"
